// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUTmxbPzmxQ74i2peGV6IGTQo0rrz-FM',
    appId: '1:651200089794:web:0953aecdd5acb98b95b55b',
    messagingSenderId: '651200089794',
    projectId: 'bus-tracking-eae81',
    authDomain: 'bus-tracking-eae81.firebaseapp.com',
    databaseURL: 'https://bus-tracking-eae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-tracking-eae81.firebasestorage.app',
    measurementId: 'G-1FG8KLPCJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeYthKivtakn57vclFj8_PsBkRfMZbZs',
    appId: '1:651200089794:android:f66fa587906721e895b55b',
    messagingSenderId: '651200089794',
    projectId: 'bus-tracking-eae81',
    databaseURL: 'https://bus-tracking-eae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-tracking-eae81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmrFAPxXLj9qH1VnLheQwg9fSAFylqcE4',
    appId: '1:651200089794:ios:3b425cddca730ad795b55b',
    messagingSenderId: '651200089794',
    projectId: 'bus-tracking-eae81',
    databaseURL: 'https://bus-tracking-eae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-tracking-eae81.firebasestorage.app',
    iosBundleId: 'com.example.busTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmrFAPxXLj9qH1VnLheQwg9fSAFylqcE4',
    appId: '1:651200089794:ios:3b425cddca730ad795b55b',
    messagingSenderId: '651200089794',
    projectId: 'bus-tracking-eae81',
    databaseURL: 'https://bus-tracking-eae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-tracking-eae81.firebasestorage.app',
    iosBundleId: 'com.example.busTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmUTmxbPzmxQ74i2peGV6IGTQo0rrz-FM',
    appId: '1:651200089794:web:c39411ff48013d0295b55b',
    messagingSenderId: '651200089794',
    projectId: 'bus-tracking-eae81',
    authDomain: 'bus-tracking-eae81.firebaseapp.com',
    databaseURL: 'https://bus-tracking-eae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-tracking-eae81.firebasestorage.app',
    measurementId: 'G-W7KJPXTCND',
  );
}
